### ISSUE TITLE
config instead of __init__.py

### ISSUE THREAD

**Issue by galantra** [trgkanki/noeasy#1]
# Feature request

## Problem description

1.5 s is a tad too long for me. I've set it to 1 s and this feels apppropriate. 

This has to be done by directly editing __init__.py.  I think this is a bit too advances for many users.

## Suggested solution

So my suggestion is: that the delay (time barrier, if you will) can be set in the add-ons window config.

**Comment by phu54321** [comment]
I thought i've already committed this, but apparently havent.
Commiting now
